# Generated by Django 4.1.5 on 2023-04-07 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseTracker', '0002_transactionrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankKeyword',
            fields=[
                ('bank', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('key_word', models.CharField(max_length=100)),
                ('key_word_category', models.CharField(choices=[('trash_value', 'Trash Value'), ('parse_value', 'Parse Value')], max_length=50)),
            ],
        ),
    ]
