# Generated by Django 4.1.5 on 2023-04-08 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseTracker', '0003_bankkeyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_preset', models.BooleanField()),
                ('is_group', models.BooleanField()),
                ('account_type', models.CharField(blank=True, max_length=100, null=True)),
                ('parent_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='ExpenseTracker.accountcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('bank_code', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_preset', models.BooleanField()),
                ('dashboard_name', models.CharField(max_length=255)),
                ('dashboard_info', models.TextField()),
                ('dashboard_desc', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_dashboard', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StatementParser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.TextField()),
                ('category', models.CharField(choices=[('trash_value', 'Trash Value'), ('parse_value', 'Parse Value')], max_length=50)),
                ('bank_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parse_value', to='ExpenseTracker.bank')),
            ],
        ),
        migrations.DeleteModel(
            name='BankKeyword',
        ),
        migrations.RenameField(
            model_name='transactionrecord',
            old_name='entry_type',
            new_name='entry',
        ),
        migrations.AddField(
            model_name='transactionrecord',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionrecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transactionrecord',
            name='account_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_transaction', to='ExpenseTracker.accountcategory'),
        ),
        migrations.AddField(
            model_name='transactionrecord',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_transaction', to='ExpenseTracker.bank'),
        ),
    ]
