# Generated by Django 4.1.5 on 2023-05-27 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseTracker', '0004_accountcategory_bank_dashboard_statementparser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statementparser',
            name='is_preset',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='statementparser',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_parser', to=settings.AUTH_USER_MODEL),
        ),
    ]
