# Generated by Django 4.1.5 on 2023-07-17 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseTracker', '0005_statementparser_is_preset_statementparser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='id',
        ),
        migrations.RemoveField(
            model_name='transactionrecord',
            name='id',
        ),
        migrations.AddField(
            model_name='dashboard',
            name='dashboard_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionrecord',
            name='transaction_id',
            field=models.AutoField(default=2, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
